services:
  # TODO
  #  projects-service:
  #    image: fulib/fulib.org-projects-service
  #    depends_on:
  #      - database
  #    build:
  #      context: services/
  #      args:
  #        SERVICE: projects
  #    environment:
  #      FULIB_PROJECTS_DATA_DIR: /projects/data
  #      FULIB_PROJECTS_PROXY_URL: http://localhost:45445
  #      MONGO_URI: mongodb://database:27017/fulib-org
  #      DOCKER_HOST: projects-runtime
  #      DOCKER_PORT: 2376
  #    ports:
  #      - '6266:3000'
  #    volumes:
  #      - '/var/run/docker.sock:/var/run/docker.sock'
  projects-proxy:
    image: fulib/fulib.org-projects-proxy
    build:
      context: projects/
      dockerfile: proxy/Dockerfile
    restart: unless-stopped
    ports:
      - "13147:80"
    networks:
      - projects
  # TODO
  #  projects-runtime:
  #    build: .
  #    privileged: true
  #    image: fulib/fulib.org-projects-runtime
  #    environment:
  #      FULIB_PROJECTS_PROXY_IMAGE: fulib/fulib.org-projects-proxy
  #      FULIB_PROJECTS_CONTAINER_IMAGE: fulib/fulib.org-projects
  #    ports:
  #      - "45445:8080"
networks:
  projects:
