apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fulib-ingress
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-keycloak
                port:
                  name: http
          {{- range $k, $service := .Values.services.list }}
          {{- range $service.endpoints }}
          - path: {{ . | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-{{ $service.name }}-service
                port:
                  name: http
          {{- end}}
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  name: http
